### ISSUE TITLE
FailedToListQuotas Error Formatted incorrectly 

### ISSUE THREAD

**Issue by ssjohnson** [thought-machine/aws-service-quotas-exporter#26]
in `/pkg/service_exporter`, the error on line 179 is formatted incorrectly.

```	
if err != nil {
	return nil, errors.Wrapf(ErrFailedToListQuotas, "%w", err)
}
```

Wrapf does not accept the %w formatter, only Errorf and Newf do. This results in: 

`time="2022-02-02T19:52:39Z" level=fatal msg="Could not retrieve quotas and limits: %!w(*awserr.baseError=&{RequestError send request failed [0xc000020ba0]}): failed to list quotas"`

**Comment by idgenchev** [comment]
Closing this as the incorrectly formatted error comes from the AWS SDK.
