### ISSUE TITLE
`servicequotas.InvalidPaginationTokenException` - failed to list quotas

### ISSUE THREAD

**Issue by peterbueschel** [thought-machine/aws-service-quotas-exporter#31]
Hi,

thank you for this project, it helps us to monitor ASGs and IP-pools.
But since the 6th of Dec. we are getting frequently the following error message:

`time="..." level=fatal msg="Could not retrieve quotas and limits: %!w(*servicequotas.InvalidPaginationTokenException=&{{} {400 ...} ...}): failed to list quotas"`

Which leads to a crash of the exporter.

Looks like, the error comes from this [call](https://github.com/thought-machine/aws-service-quotas-exporter/blob/24b0c216e6724ea506cba6f1a6a8a9a3f981b749/pkg/service_quotas/service_quotas.go#L156)

`err := s.quotasService.ListServiceQuotasPages(params,...`

This in turn comes [from](https://github.com/thought-machine/aws-service-quotas-exporter/blob/24b0c216e6724ea506cba6f1a6a8a9a3f981b749/pkg/service_quotas/service_quotas.go#L93):

`quotasService            servicequotasiface.ServiceQuotasAPI`

Related to the [AWS SDK docs](https://docs.aws.amazon.com/sdk-for-go/api/service/servicequotas/servicequotasiface/):
_Package servicequotasiface provides an interface to enable mocking the Service Quotas service client for testing your code.
It is important to note that this interface will have breaking changes when the service model is updated and adds new API operations, paginators, and waiters._

So, maybe (I haven't dive that deep into the code) a SDK update is required.

Cheers,
Peter

**Comment by idgenchev** [comment]
Hi @peterbueschel thanks for raising this!

Yes, an SDK update will fix this. This tool is currently using 1.33.5 (Jul 9, 2020) and the current is 1.44.x. PRs are more than welcome :) Having said that, it's been on my list for a while to update the dependencies for this tool, so will do it if/when I manage to get some time.
