### ISSUE TITLE
error `x509: certificate signed by unknown authority` when using container image v1.3.0

### ISSUE THREAD

**Issue by peterbueschel** [thought-machine/aws-service-quotas-exporter#37]
Hi,

> just for the paper work, I add next to [PR](https://github.com/thought-machine/aws-service-quotas-exporter/pull/36) also an issue report here.

With the `v1.3.0` we are getting the following error message:

```console
time="2022-12-..." level=fatal msg="Could not retrieve quotas and limits: failed to list quotas: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: 

Post "https://sts.amazonaws.com/": x509: certificate signed by unknown authority"
```

A possible fix is provided in this PR: https://github.com/thought-machine/aws-service-quotas-exporter/pull/36

**Comment by idgenchev** [comment]
resolved in #36
